Repository SwEnt-Fall-2024-Group-22/Cyrcle, pull requests merged in 2024-10, with the labels that each got.

#2 Guideline extension and App logo sketch
  app/src/main/res/drawable/app_logo.png
  docs/Guidelines.md
Labels: documentation

#3 bugfix: Change package name and fix deprecated build option
  .github/workflows/CI.yaml
  app/build.gradle.kts
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
Labels: bug

#9 dev: end the CI, update secret and small documentation changes
  .github/workflows/CI.yaml
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  docs/Architecture.md
Labels: bug

#13 fix: correct NavHost declaration
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
Labels: bug

#14 Feature: Login screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/SignInTest.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
  app/src/main/res/values/strings.xml
Labels: feature

#12 MapScreen and MapBox implementation and API KEY Management
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  build.gradle.kts
  settings.gradle.kts
Labels: feature

#18 Feature parking dataclass
  app/build.gradle.kts
  app/src/main/java/com/github/se/cyrcle/model/parking/Parking.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingTest.kt
  gradle/libs.versions.toml
Labels: feature

#21 Feature image repository
  app/src/main/java/com/github/se/cyrcle/model/parking/ImageRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ImageRepositoryCloudStorage.kt
Labels: feature

#22 Parking view model
  .github/workflows/CI.yaml
  app/src/androidTest/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/model/parking/TestInstancesParking.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
Labels: feature

#25 feat: implement basic Composables
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ButtonTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/InputTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ToastTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/BottomNavBarTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/CarouselTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/DatePickerTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/GalleryTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Color.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Input.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Toast.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/BottomNavigationBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/Carousel.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/DatePicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/Gallery.kt
Labels: feature

#26 Bugfix navigation
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/ui/card/CardScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/List.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/TopAppBar.kt
Labels: bug, feature

#38 fix: intermittent Authentication tests error
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/SignInTest.kt
Labels: bug

#36 Improve the map style
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/AddButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/ZoomControls.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/preview/Preview.kt
  gradle/libs.versions.toml
Labels: feature

#39 Fix: use our colors for the theme instead of default one
  app/src/main/java/com/github/se/cyrcle/ui/theme/Theme.kt
Labels: bug

#33 Optimize and finalize ViewModel
  app/src/androidTest/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestoreTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/model/parking/TestInstancesParking.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/TestInstancesParking.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
Labels: bug, feature

#44 Integrate MapBox Points in the code
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestoreTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/Parking.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/TestInstancesParking.kt
  app/src/main/java/com/github/se/cyrcle/ui/card/CardScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/List.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
  gradle/libs.versions.toml
Labels: feature

#47 Display markers and manage them
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/ZoomControls.kt
  app/src/main/res/drawable/red_marker.png
Labels: feature

#51 Navigation for the process of adding new parking spots
  app/src/androidTest/java/com/github/se/cyrcle/ui/add/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/ui/add/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/add/LocationPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/AddButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
Labels: feature

#52 Implement a ViewModel for Reviews
  app/src/androidTest/java/com/github/se/cyrcle/model/review/ReviewViewModelTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/model/review/TestInstancesReview.kt
  app/src/main/java/com/github/se/cyrcle/model/review/Review.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
Labels: feature

#56 Optimize map and implement Firestore caching
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: feature

#62 Patch to prevent query density
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: bug

#53 Test coverageee
  app/src/androidTest/java/com/github/se/cyrcle/MainActivityTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestoreTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/model/review/ReviewViewModelTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/card/CardScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/TestInstancesParking.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/cyrcle/ui/card/CardScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/ZoomControls.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/TopAppBar.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestoreTest.kt
Labels: test

#61 Implement user data class and repository interface.
  app/src/main/java/com/github/se/cyrcle/model/user/User.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepository.kt
Labels: feature

#43 General Theme improvement, with improved Atom and Molecule
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ButtonTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/InputTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ToastTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/BottomNavigationBarTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/CarouselTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/DatePickerTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/GalleryTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/TopAppBarTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/cyrcle/ui/card/CardScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Color.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Input.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Toast.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/BottomNavigationBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/Carousel.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/DatePicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/Gallery.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/TopAppBar.kt
Labels: feature

#74 Fixes the Release workflow
  .github/workflows/Release.yaml
Labels: bug

#82 Rework user backend
  app/src/androidTest/java/com/github/se/cyrcle/model/user/UserRepositoryFirestoreTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
  app/src/main/java/com/github/se/cyrcle/model/user/User.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserTestInstances.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
Labels: refactor

#88 Refactor the (de)serialization using an adapter
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestore.kt
Labels: refactor

#90 Feature: Dependency injection
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/cyrcle/MainActivityTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/HiltTestRunner.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/MockRepoModule.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockImageRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockParkingRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockReviewRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockUserRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/SignInTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/cyrcle/CyrcleApp.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/di/AppModule.kt
  app/src/main/java/com/github/se/cyrcle/di/RepoModule.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ImageRepositoryCloudStorage.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepositoryFirestore.kt
  build.gradle.kts
Labels: feature, test

#84 Address Model, Repository, and ViewModel for Reverse Geocoding
  app/src/androidTest/java/com/github/se/cyrcle/di/MockRepoModule.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockAddressRepository.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/di/AppModule.kt
  app/src/main/java/com/github/se/cyrcle/di/RepoModule.kt
  app/src/main/java/com/github/se/cyrcle/model/address/Address.kt
  app/src/main/java/com/github/se/cyrcle/model/address/AddressRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/address/AddressRepositoryNominatim.kt
  app/src/main/java/com/github/se/cyrcle/model/address/AddressViewModel.kt
  app/src/test/java/com/github/se/cyrcle/model/address/AddressRepositoryNominatimTest.kt
  app/src/test/java/com/github/se/cyrcle/model/address/AddressTest.kt
  app/src/test/java/com/github/se/cyrcle/model/address/AddressViewModelTest.kt
Labels: feature

#91 Implement MapViewModel
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapConfig.kt
  app/src/test/java/com/github/se/cyrcle/model/map/MapViewModelTest.kt
Labels: feature, test

#92 Adding Parking : The Location Picker Screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/add/AddScreensNavigationTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/Parking.kt
  app/src/main/java/com/github/se/cyrcle/ui/add/LocationPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/add/location/LocationPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/add/location/LocationPickerBottomBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/add/location/LocationPickerTopBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/add/location/overlay/Crosshair.kt
  app/src/main/java/com/github/se/cyrcle/ui/add/location/overlay/RectangleSelection.kt
Labels: feature

#93 Adding Parking : The Attributes Picker Screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/add/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPickerBottomBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPickerTopBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/overlay/Crosshair.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/overlay/RectangleSelection.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/BooleanRadioButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/EnumDropDown.kt
Labels: feature

#113 refactor: refactor mapscreen
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: refactor

#114 Link the markers to the parking view model
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: feature

#115 Integrate title suggestion in attribute picker
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/model/address/Address.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/test/java/com/github/se/cyrcle/model/address/AddressTest.kt
Labels: feature

#106 Implement user favourite parkings
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockParkingRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
Labels: feature

#118 Implement Reviews into the App
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/ReviewScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/Parking.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/card/CardScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
Labels: feature

#111 User Profile Screen First Version
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
Labels: feature

#124 View All Reviews for a Parking
  app/src/androidTest/java/com/github/se/cyrcle/ui/card/CardScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/review/TestInstancesReview.kt
  app/src/main/java/com/github/se/cyrcle/ui/card/CardScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
Labels: feature

#120 Feature theme improvement
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/cyrcle/MainActivityTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/ColorTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/ThemePreview.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/ThemeTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ButtonTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/InputTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/BooleanRadioButtonTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/BottomNavigationBar.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/EnumDropDownTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/TopAppBarTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Color.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Theme.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/BooleanRadioButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/BottomNavigationBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/EnumDropDown.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/TopAppBar.kt
  app/src/main/res/drawable/app_logo.png
  app/src/main/res/drawable/app_logo_name.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi/app_logo.xml
  app/src/main/res/mipmap-anydpi/app_logo_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/app_logo.webp
  app/src/main/res/mipmap-hdpi/app_logo_round.webp
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/app_logo.webp
  app/src/main/res/mipmap-mdpi/app_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/app_logo.webp
  app/src/main/res/mipmap-xhdpi/app_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/app_logo.webp
  app/src/main/res/mipmap-xxhdpi/app_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/app_logo.webp
  app/src/main/res/mipmap-xxxhdpi/app_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/test/java/com/github/se/cyrcle/ui/theme/ColorTest.kt
  app/src/test/java/com/github/se/cyrcle/ui/theme/ThemeTest.kt
Labels: refactor

#126 User profile favorite parkings
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
Labels: feature

#125 Mix Atoms and Molecules into codebase
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapButtonsPreview.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ButtonTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/TextTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPickerBottomBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPickerTopBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/overlay/RectangleSelection.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/cyrcle/ui/card/CardScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/AddButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/ZoomControls.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Type.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Text.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/BooleanRadioButton.kt
Labels: refactor
