Repository SwEnt-Fall-2024-Group-22/Cyrcle, pull requests merged in 2024-12, with the labels that each got.

#333 Review Interaction - Likes and Dislikes Feature
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/review/Review.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/review/ReviewViewModelTest.kt
Labels: feature

#332 Add and Manage zones
  app/src/androidTest/java/com/github/se/cyrcle/ui/zone/ZoneManagerScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/zone/ZoneSelectionScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/zone/Zone.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPickerBottomBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/overlay/RectangleSelection.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Input.kt
  app/src/main/java/com/github/se/cyrcle/ui/zone/ZoneManagerScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/zone/ZoneSelectionScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature

#330 Feature: Room for persistent storage
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/cyrcle/io/PreferenceStorageTest.kt
  app/src/main/java/com/github/se/cyrcle/io/datastore/PreferenceStorage.kt
  app/src/main/java/com/github/se/cyrcle/io/datastore/ProtoGenericSerializer.kt
  app/src/main/java/com/github/se/cyrcle/io/serializer/ParkingAdapter.kt
  app/src/main/java/com/github/se/cyrcle/io/serializer/ParkingSetAdapter.kt
  app/src/main/java/com/github/se/cyrcle/io/serializer/PointAdapter.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/Tile.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/TileDao.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/TileDatabase.kt
  app/src/test/java/com/github/se/cyrcle/io/Settings.kt
  app/src/test/java/com/github/se/cyrcle/io/datastore/SettingsSerializerTest.kt
  app/src/test/java/com/github/se/cyrcle/io/serializer/ParkingSerializerTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/TileManagerTest.kt
  gradle/libs.versions.toml
Labels: feature

#341 Filters on MapScreen
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/FilterTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/Filter.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
Labels: feature

#342 Feature Search Bar for List Screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/FilterTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/address/Address.kt
  app/src/main/java/com/github/se/cyrcle/model/address/AddressRepositoryNominatim.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/Filter.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/address/AddressRepositoryNominatimTest.kt
Labels: feature

#345 Re-enable rotation on the Map and display parkings in Location Picker screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapButtonsPreview.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/online/ParkingRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/ZoomControls.kt
Labels: bug

#351 Polish the MapBoxMap
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: feature

#352 Bugfix 343: Replace XML-based preview cards with Composable overlay
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug

#350 Show in Map button
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/test/java/com/github/se/cyrcle/model/map/MapViewModelTest.kt
Labels: bug

#357 Revert "Show in Map button"
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/test/java/com/github/se/cyrcle/model/map/MapViewModelTest.kt
Labels: bug, test

#358 Feature list my reviews
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/review/TestInstancesReview.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature

#372 Improve serializers when dealing with legacy
  app/src/main/java/com/github/se/cyrcle/io/serializer/ParkingAdapter.kt
  app/src/main/java/com/github/se/cyrcle/io/serializer/StringListAdapter.kt
Labels: bug

#376 Add Tab Layout for User Profile Screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/DisplayProfileComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature, UI/UX

#373 Feature offline parkings
  app/src/main/java/com/github/se/cyrcle/model/network/ConnectivityObserver.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
Labels: feature

#384 Enhanced Favorite Parking Cards and Slideable Tab Layout
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/res/values/strings.xml
Labels: UI/UX

#310 Fix UI gamblingscreen
  app/src/androidTest/java/com/github/se/cyrcle/ui/gambling/GamblingScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/gambling/GamblingScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature, test, refactor, UI/UX

#395 Third end-to-end test
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/InviteToAuthScreen.kt
Labels: test

#394 Enhance Map Screen Suggestions Menu
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/address/AddressRepositoryNominatim.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: bug, UI/UX

#400 Improve Sign-In screen UI
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignInScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: refactor, UI/UX

#359 Feature go to map button Bis
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/test/java/com/github/se/cyrcle/model/map/MapViewModelTest.kt
Labels: test

#406 Forth E2E test
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/model/review/TestInstancesReview.kt
Labels: test

#403 Let Users see and Delete their images
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenAlertDialogTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/AdminScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ImageReportScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ParkingReportScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ReviewReportScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ViewReportsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/ReviewScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/FilterTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/zone/ZoneManagerScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/zone/ZoneSelectionScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/io/serializer/ParkingAdapter.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/Parking.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/TestInstancesParking.kt
  app/src/main/java/com/github/se/cyrcle/model/user/User.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsAlertDialogShowImage.kt.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/report/ViewReportsScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
Labels: feature

#405 Feature rewards gambling 2
  app/src/androidTest/java/com/github/se/cyrcle/ui/gambling/GamblingScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/user/User.kt
  app/src/main/java/com/github/se/cyrcle/ui/gambling/GamblingScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/DisplayProfileComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature

#416 Upscale small pictures
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsAlertDialogShowImage.kt.kt
Labels: UI/UX

#420 LET IT SNOW ❄️
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/sensor/ShakeDetector.kt
  app/src/main/java/com/github/se/cyrcle/ui/grigris/SnowFall.kt
  app/src/main/res/values/strings.xml
Labels: feature, UI/UX

#415 Progress bar for download
  app/src/androidTest/java/com/github/se/cyrcle/ui/zone/ZoneSelectionScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapConfig.kt
  app/src/main/java/com/github/se/cyrcle/ui/zone/ZoneSelectionScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature

#426 Update/enhance the e2e tests
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
Labels: test, refactor

#425 Bugfix MapScreen network changes
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: bug

#427 Make Reported Objects Visible from Admin Screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/AdminScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/report/AdminScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature

#428 Code Clean Up
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockOfflineParkingRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockReportedObjectsRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/io/PreferenceStorageTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/RackInfoTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenAlertDialogTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/AdminScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ImageReportScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ParkingReportScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ReportScreenAlertDialogTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ReviewReportScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ViewReportsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/ColorTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/ThemeTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/BooleanRadioButtonTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/EnumDropDownTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/ReportScreenMoleculesTest.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/model/address/AddressRepositoryNominatim.kt
  app/src/main/java/com/github/se/cyrcle/model/network/ConnectivityObserver.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/online/ParkingRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/report/ReportedObjectViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/gambling/GamblingScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/grigris/SnowFall.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/report/AdminScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/report/ImageReportScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/report/ParkingReportScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/report/ViewReportsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Color.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Input.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/BooleanRadioButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/Filter.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/ReportScreenMolecules.kt
  app/src/main/res/drawable/card_background.xml
  app/src/main/res/drawable/red_marker.png
  app/src/main/res/layout/item_callout_view.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/authentication/AuthenticationRepositoryGoogleTest.kt
  app/src/test/java/com/github/se/cyrcle/model/image/ImageRepositoryCloudStorageTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/report/ReportedObjectRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/review/ReviewViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/CoinViewModelTest.kt
Labels: documentation, refactor

#418 Assert a minimum area for new parking
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPickerBottomBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/overlay/RectangleSelection.kt
  app/src/main/res/values/strings.xml
Labels: feature

#432 Bugfix delete sonar cloud
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: refactor

#419 Go to map from zone manager screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/zone/ZoneManagerScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/zone/ZoneManagerScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature

#422 Polish list screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/Filter.kt
  app/src/main/res/values/strings.xml
Labels: refactor, UI/UX

#437 Fix: Number of reviews on PreviewCard
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: bug

#430 README refresh
  README.md
  readme_rsc/app_arch_m2.png
  readme_rsc/app_arch_m3.png
Labels: documentation

#439 Attemp to bugfix missing credentials
  app/src/main/java/com/github/se/cyrcle/model/authentication/AuthenticationRepositoryGoogle.kt
Labels: bug

#353 Where's my Bike feature
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/zone/ZoneManagerScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/io/datastore/ProtoGenericSerializer.kt
  app/src/main/java/com/github/se/cyrcle/model/map/BikeLocationViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/zone/ZoneManagerScreen.kt
  app/src/main/res/drawable/bike_location_marker.png
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/io/Settings.kt
  app/src/test/java/com/github/se/cyrcle/model/map/MapViewModelTest.kt
Labels: feature

#408 Tutorial screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/CreateProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/tutorial/TutorialScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/tutorial/TutorialScreen.kt
  app/src/main/res/drawable/tutorial_list_screen.png
  app/src/main/res/drawable/tutorial_map_screen.png
  app/src/main/res/values/strings.xml
Labels: feature
