Repository SwEnt-Fall-2024-Group-22/Cyrcle, pull requests merged in 2024-11, with the labels that each got.

#132 Sign the APK
  .github/workflows/CI.yaml
  .github/workflows/Release.yaml
  app/build.gradle.kts
Labels: bug

#133 Add a tile manager to reduce number of requests to firestore
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/Tile.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/res/drawable/dot.png
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/TileManagerTest.kt
Labels: refactor

#139 Rework list screen UI and add infinite scroll
  app/src/androidTest/java/com/github/se/cyrcle/MainActivityTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ButtonTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/TestInstancesParking.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
Labels: feature, refactor

#142 Feature add firebase rules
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockUserRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/ReviewScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/user/User.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserRepositoryFirestoreTest.kt
Labels: feature

#134 BugFix Preview Card don't display after adding a review
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: bug

#148 Restrain Anonymous Users
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/card/CardScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapButtonsPreview.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/CreateProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ButtonTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/GoogleSignInButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/cyrcle/ui/card/CardScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/AddButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/ZoomControls.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Color.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/TopAppBar.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
Labels: feature

#59 Documentation for Milestone 1
  README.md
  docs/Architecture.md
  docs/DetailedFeatures.md
  docs/Guidelines.md
Labels: documentation

#154 EnumDropDown text fix
  app/src/main/java/com/github/se/cyrcle/model/parking/Parking.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/EnumDropDown.kt
Labels: bug

#153 String refactoring
  app/src/androidTest/java/com/github/se/cyrcle/ui/card/CardScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPickerBottomBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPickerTopBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/overlay/RectangleSelection.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/GoogleSignInButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/cyrcle/ui/card/CardScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/overlay/ZoomControls.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/BooleanRadioButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/TopAppBar.kt
  app/src/main/res/values/strings.xml
Labels: refactor

#151 Integrate user viewmodel in profile screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/card/CardScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/TestInstancesParking.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
Labels: feature, test, refactor

#156 Increase App UI Cohesion
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/ReviewScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/ColorTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ButtonTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
Labels: refactor

#150 Geolocalisation of the user
  app/src/androidTest/java/com/github/se/cyrcle/di/MockPermissionsModule.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockPermissionHandler.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/di/PermissionModule.kt
  app/src/main/java/com/github/se/cyrcle/permission/PermissionHandler.kt
  app/src/main/java/com/github/se/cyrcle/permission/PermissionHandlerInterface.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: feature

#147 Refactor getKClosestParkings
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockParkingRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/TestInstancesParking.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/Tile.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/TileManagerTest.kt
Labels: refactor

#157 Refactor card screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/res/values/strings.xml
Labels: refactor

#158 Implement Logging for Reviews
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/review/Review.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/review/TestInstancesReview.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/review/ReviewRepositoryFirestoreTest.kt
Labels: feature

#173 BugFix : Display user localisation
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/permission/PermissionHandler.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: bug

#179 Text input verification
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/ReviewScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ButtonTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/InputTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Input.kt
  app/src/main/res/values/strings.xml
Labels: feature

#170 fix: solve issue 167
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
Labels: bug, refactor

#176 Feature log out
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/AuthenticatorMock.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/AuthenticatorDefaultTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/AuthenticatorImplTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/Authenticator.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/AuthenticatorImpl.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignInScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
Labels: feature

#178 Divide the user information into a public and a private part
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockUserRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/user/TestInstancesUser.kt
  app/src/main/java/com/github/se/cyrcle/model/user/User.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/AuthenticatorImpl.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignInScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
Labels: bug, feature, refactor

#185 Ensure synchronisation between the Viewmodel and the UI
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
Labels: bug

#186 Feature parking size verification
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/Parking.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPickerBottomBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/overlay/RectangleSelection.kt
  app/src/main/res/values/strings.xml
Labels: feature

#192 Hide centering button when location is disabled
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: bug

#191 fix : back stack correctly clears itself.
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/CreateProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/ReviewScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
Labels: bug, refactor

#189 Add Functionality AllReviewsScreen
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
Labels: feature

#194 Toggle between Rectangles and Markers on map
  app/src/main/java/com/github/se/cyrcle/model/parking/Parking.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature

#195 List screen based on user's actual location
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: feature

#199 Theme
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/molecules/EnumDropDownTest.kt
  app/src/main/app_logo-playstore.png
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/LocationPickerBottomBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/location/overlay/RectangleSelection.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/Authenticator.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Color.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Theme.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Input.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Text.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/BooleanRadioButton.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/BottomNavigationBar.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/EnumDropDown.kt
  app/src/main/res/drawable/app_logo_background.xml
  app/src/main/res/drawable/app_logo_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/app_logo.xml
  app/src/main/res/mipmap-anydpi-v26/app_logo_round.xml
  app/src/main/res/mipmap-anydpi/app_logo.xml
  app/src/main/res/mipmap-anydpi/app_logo_round.xml
  app/src/main/res/mipmap-hdpi/app_logo.webp
  app/src/main/res/mipmap-hdpi/app_logo_round.webp
  app/src/main/res/mipmap-mdpi/app_logo.webp
  app/src/main/res/mipmap-mdpi/app_logo_round.webp
  app/src/main/res/mipmap-xhdpi/app_logo.webp
  app/src/main/res/mipmap-xhdpi/app_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/app_logo.webp
  app/src/main/res/mipmap-xxhdpi/app_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/app_logo.webp
  app/src/main/res/mipmap-xxxhdpi/app_logo_round.webp
  app/src/test/java/com/github/se/cyrcle/ui/theme/ThemeTest.kt
Labels: feature, refactor

#201 Favorite Icon Action In ParkingDetailScreen
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature

#203 Light UI changes for better user experience
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/ReviewScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/molecules/TopAppBar.kt
Labels: refactor

#204 Coin system skeleton
  app/src/main/java/com/github/se/cyrcle/model/user/CoinViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/user/TestInstancesUser.kt
  app/src/main/java/com/github/se/cyrcle/model/user/User.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/user/Wallet.kt
  app/src/test/java/com/github/se/cyrcle/model/user/CoinViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/WalletTest.kt
Labels: feature

#242 Refactor permissions for tests
  app/src/androidTest/java/com/github/se/cyrcle/di/MockPermissionsModule.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockPermissionHandler.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/di/AuthenticatorModule.kt
  app/src/main/java/com/github/se/cyrcle/di/PermissionModule.kt
  app/src/main/java/com/github/se/cyrcle/permission/PermissionHandler.kt
  app/src/main/java/com/github/se/cyrcle/permission/PermissionHandlerImpl.kt
  app/src/main/java/com/github/se/cyrcle/permission/PermissionHandlerInterface.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/test/java/com/github/se/cyrcle/permission/PermissionHandlerTest.kt
Labels: refactor

#248 Refactor profile screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/CreateProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/EditProfileComponentTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileImageComponentTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/DisplayProfileComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/EditProfileComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileImageComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: refactor

#243 Rework list screen and add pin icon in detail screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Color.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/Theme.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/res/values/strings.xml
Labels: UI

#249 Prepare the user data class for pictures
  app/src/main/java/com/github/se/cyrcle/model/user/TestInstancesUser.kt
  app/src/main/java/com/github/se/cyrcle/model/user/User.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/DisplayProfileComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/EditProfileComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileImageComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
Labels: feature, refactor

#252 Profile pictures are persistent
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignInScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/DisplayProfileComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/EditProfileComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
Labels: feature

#258 Improve UI of the preview card.
  app/src/main/res/drawable/card_background.xml
  app/src/main/res/layout/item_callout_view.xml
Labels: UI

#256 bugfix : non persistent state in view model during Configuration changes
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/model/CustomViewModelFactory.kt
Labels: bug

#255 Feature CreateProfileScreen
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/AuthenticatorMock.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockUserRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/CreateProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/EditProfileComponentTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/InviteToAuthScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/Authenticator.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignInScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/EditProfileComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/InviteToAuthScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Input.kt
  app/src/main/res/values/strings.xml
Labels: feature

#259 Add Rack Type Help Screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/RackInfoTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/RackInfo.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
  app/src/main/res/drawable/rack.jpg
  app/src/main/res/values/strings.xml
Labels: feature

#263 Dialog box to avoid accidental signOut
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature

#244 Feature add parking details navigation
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
Labels: feature

#267 fix: transformPathToUrl crashes the app with old user
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/SignInTest.kt
  app/src/main/java/com/github/se/cyrcle/model/user/User.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
Labels: bug

#265 Reporting Logic for Parkings And Reviews
  app/src/androidTest/java/com/github/se/cyrcle/di/MockRepoModule.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockParkingRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockReportedObjectsRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockReviewRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/ReviewScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/di/RepoModule.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/Parking.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/report/ReportedObject.kt
  app/src/main/java/com/github/se/cyrcle/model/report/ReportedObjectRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/report/ReportedObjectRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/report/TestInstancesReportedObject.kt
  app/src/main/java/com/github/se/cyrcle/model/review/Review.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/report/ReportedObjectRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/review/ReviewRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/review/ReviewViewModelTest.kt
Labels: feature

#280 Check that users exist for sign in and account creation
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockUserRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/CreateProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/ReviewScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/testEnd2End/MainActivityTest.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignInScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/user/CoinViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
Labels: feature

#288 Update Google SignIn API
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/AuthenticatorMock.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/AuthenticatorImplTest.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/Authenticator.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/AuthenticatorImpl.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignInScreen.kt
  gradle/libs.versions.toml
Labels: refactor

#290 Optimize Favorite Parking State Management in UserViewModel
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
Labels: bug, refactor

#284 Display all parkings in List Screen with pin distinction
  app/src/main/java/com/github/se/cyrcle/ui/list/ListScreen.kt
Labels: UI/UX

#285 Upload&Download Pictures for parkings
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockImageRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenAlertDialogTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/image/ImageRepositoryCloudStorage.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/TestInstancesParking.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsAlertDialog.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
Labels: feature, UI/UX

#294 Interactions with rectangles
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
Labels: feature

#268 Feature gambling
  app/src/androidTest/java/com/github/se/cyrcle/ui/gambling/GamblingScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/gambling/GamblingScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature

#292 Refactor Sign In Process
  app/src/androidTest/java/com/github/se/cyrcle/di/MockAuthenticatorModule.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/AuthenticatorMock.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockAuthenticationRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/addParking/AddScreensNavigationTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/AuthenticatorDefaultTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/AuthenticatorImplTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/authentication/SignInTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/list/ListScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/CreateProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/ViewProfileScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/ReviewScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/MainActivity.kt
  app/src/main/java/com/github/se/cyrcle/di/AuthenticatorModule.kt
  app/src/main/java/com/github/se/cyrcle/model/address/AddressViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/authentication/AuthenticationRepository.kt
  app/src/main/java/com/github/se/cyrcle/model/authentication/AuthenticationRepositoryGoogle.kt
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewViewModel.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/Authenticator.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/AuthenticatorImpl.kt
  app/src/main/java/com/github/se/cyrcle/ui/authentication/SignInScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/test/java/com/github/se/cyrcle/model/authentication/AuthenticationRepositoryGoogleTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/CoinViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
Labels: refactor

#297 Add Personal Notes Feature for Parking Details
  app/src/androidTest/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/model/user/User.kt
  app/src/main/java/com/github/se/cyrcle/model/user/UserViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Input.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/user/UserViewModelTest.kt
Labels: feature

#269 File IO
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/cyrcle/io/PreferenceStorageTest.kt
  app/src/main/java/com/github/se/cyrcle/io/MapTileStorage.kt
  app/src/main/java/com/github/se/cyrcle/io/PreferenceStorage.kt
  app/src/main/java/com/github/se/cyrcle/io/ProtoGenericSerializer.kt
  app/src/test/java/com/github/se/cyrcle/io/MapTileStorageTest.kt
  app/src/test/java/com/github/se/cyrcle/io/Settings.kt
  app/src/test/java/com/github/se/cyrcle/io/SettingsSerializerTest.kt
  app/src/test/java/com/github/se/cyrcle/io/TestClassForIo.kt
  gradle/libs.versions.toml
Labels: feature

#298 BugFix : advanced Mode and camera state not persistent across Screen navigation
  app/src/main/java/com/github/se/cyrcle/model/map/MapViewModel.kt
  app/src/main/java/com/github/se/cyrcle/ui/addParking/attributes/AttributesPicker.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
Labels: bug, refactor

#299 Add Report Screens
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockParkingRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/di/mocks/MockReviewRepository.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ParkingReportScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ReportScreenAlertDialogTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/report/ReviewReportScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/parking/Parking.kt
  app/src/main/java/com/github/se/cyrcle/model/report/ReportedObjectRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/model/review/Review.kt
  app/src/main/java/com/github/se/cyrcle/model/review/ReviewRepositoryFirestore.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/report/ParkingReportScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/report/ReportScreenAlertDialog.kt
  app/src/main/java/com/github/se/cyrcle/ui/report/ReviewReportScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/ReviewScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Text.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/cyrcle/model/parking/ParkingViewModelTest.kt
  app/src/test/java/com/github/se/cyrcle/model/report/ReportedObjectRepositoryFirestoreTest.kt
  app/src/test/java/com/github/se/cyrcle/model/review/ReviewViewModelTest.kt
Labels: feature

#326 Add check for incorect fields during account creation
  app/src/androidTest/java/com/github/se/cyrcle/ui/gambling/GamblingScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/profile/EditProfileComponentTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/CreateProfileScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/EditProfileComponent.kt
  app/src/main/java/com/github/se/cyrcle/ui/profile/ViewProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug

#325 UI rework of All Reviews screen
  app/src/androidTest/java/com/github/se/cyrcle/ui/review/AllReviewsScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/theme/atoms/ButtonTest.kt
  app/src/main/java/com/github/se/cyrcle/ui/review/AllReviewsScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/theme/atoms/Button.kt
  app/src/main/res/values/strings.xml
Labels: bug, refactor, UI/UX

#327 Preliminary setup for Zone Management.
  app/src/androidTest/java/com/github/se/cyrcle/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/zone/ZoneManagerScreenTest.kt
  app/src/androidTest/java/com/github/se/cyrcle/ui/zone/ZoneSelectionScreenTest.kt
  app/src/main/java/com/github/se/cyrcle/CyrcleNavHost.kt
  app/src/main/java/com/github/se/cyrcle/model/zone/Zone.kt
  app/src/main/java/com/github/se/cyrcle/ui/map/MapScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/cyrcle/ui/zone/ZoneManagerScreen.kt
  app/src/main/java/com/github/se/cyrcle/ui/zone/ZoneSelectionScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature
